name: check_sha256sum

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: '需要检查的tag名称'
        required: true
        default: '4.38-9760-rtm'
      

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - name: sha256sum
      run: |
        wget https://github.com/wanrenzhizun/SoftEtherVPN_Stable/archive/refs/tags/v${{ github.event.inputs.tag_name }}.tar.gz source.tar.gz
        sha256sum source.tar.gz
