name: check_sha256sum

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: '需要检查的tag名称'
        required: true
        default: 'v4.38-9760-rtm'
      

jobs:
  check:

    runs-on: ubuntu-18.04

    steps:
    - name: download
      run: wget https://github.com/wanrenzhizun/SoftEtherVPN_Stable/archive/refs/tags/${{ github.event.inputs.tag_name }}.tar.gz
    - name: sha256sum
      run: sha256sum ${{ github.event.inputs.tag_name }}.tar.gz
